- name: Set release info
  if: github.ref_name == 'qa' || github.ref_name == 'prod'
  run: |
    echo "TAG_NAME=v1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
    echo "RELEASE_NAME=Herro v1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

- name: Create QA prerelease
  if: github.ref_name == 'qa'
  uses: softprops/action-gh-release@v2
  with:
    tag_name: ${{ env.TAG_NAME }}
    name: ${{ env.RELEASE_NAME }}
    prerelease: true
    generate_release_notes: true
    files: |
      ${{ env.ZIP_NAME }}

- name: Create PROD release
  if: github.ref_name == 'prod'
  uses: softprops/action-gh-release@v2
  with:
    tag_name: ${{ env.TAG_NAME }}
    name: ${{ env.RELEASE_NAME }}
    prerelease: false
    generate_release_notes: true
    files: |
      ${{ env.ZIP_NAME }}